# Generated by Django 5.2.6 on 2025-11-05 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('reporter_name', models.CharField(blank=True, max_length=100, null=True)),
                ('reporter_phone', models.CharField(max_length=15)),
                ('complaint_description', models.TextField()),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='complaint_images/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='complaint_images/')),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('INSPECTING', 'Inspecting'), ('REPAIRING', 'Repairing'), ('COMPLETED', 'Completed')], default='SUBMITTED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('resolved_by', models.CharField(blank=True, max_length=100, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='asset.asset')),
            ],
            options={
                'verbose_name': 'Complaint',
                'verbose_name_plural': 'Complaints',
                'ordering': ['-created_at'],
            },
        ),
    ]
