# Generated by Django 5.2.6 on 2025-10-17 04:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('safety_hazard', models.CharField(choices=[('LEANING_POLE', 'Leaning Pole'), ('EXPOSED_WIRES', 'Exposed Wires'), ('SPARKING', 'Sparking'), ('CRACKED_POLE', 'Cracked Pole'), ('MISSING_COMPONENTS', 'Missing Components'), ('VEGETATION_GROWTH', 'Vegetation Growth'), ('OTHER', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('mobile_number', models.CharField(max_length=15)),
                ('otp', models.CharField(blank=True, max_length=6, null=True)),
                ('otp_verified', models.BooleanField(default=False)),
                ('otp_created_at', models.DateTimeField(blank=True, null=True)),
                ('otp_attempts', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('UNDER_REVIEW', 'Under Review'), ('ASSIGNED', 'Assigned to Technician'), ('IN_PROGRESS', 'Repair in Progress'), ('RESOLVED', 'Resolved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.CharField(max_length=20, unique=True)),
                ('asset_type', models.CharField(choices=[('ELECTRIC_POLE', 'Electric Pole'), ('TRANSFORMER', 'Transformer'), ('DISTRIBUTION_BOX', 'Distribution Box')], default='ELECTRIC_POLE', max_length=50)),
                ('location', models.TextField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('status', models.CharField(default='ACTIVE', max_length=20)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ComplaintImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='complaint_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='citizen_portal.complaint')),
            ],
        ),
        migrations.AddField(
            model_name='complaint',
            name='pole',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='citizen_portal.pole'),
        ),
    ]
