# Generated by Django 5.2.6 on 2025-10-17 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0003_alter_transformercommissioning_options_pole_latitude_and_more'),
        ('citizen_portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='pole',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='asset.pole'),
        ),
        migrations.DeleteModel(
            name='Pole',
        ),
    ]
