# Generated by Django 5.2.6 on 2025-10-04 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_class', models.CharField(choices=[('TRF', 'Transformer'), ('POL', 'Pole')], max_length=10)),
                ('asset_group', models.CharField(choices=[('UPDO', 'UPDO')], max_length=10)),
                ('asset_number', models.CharField(max_length=50)),
                ('commissioning_date', models.DateField()),
                ('commissioning_person', models.CharField(max_length=100)),
                ('dmm', models.CharField(choices=[('Option1', 'Option1'), ('Option2', 'Option2')], max_length=20)),
                ('secondary_connection', models.CharField(choices=[('SC1', 'SC1'), ('SC2', 'SC2')], max_length=20)),
                ('ct_ratio', models.CharField(max_length=20)),
                ('pt_ratio', models.CharField(max_length=20)),
            ],
        ),
    ]
