# Generated by Django 5.2.6 on 2025-11-01 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(choices=[('POLE', 'Pole'), ('TRANSFORMER', 'Transformer')], max_length=20)),
                ('asset_number', models.CharField(max_length=50, unique=True)),
                ('asset_group', models.CharField(choices=[('UPDO', 'UPDO')], max_length=10)),
                ('status', models.CharField(choices=[('PROVISIONED', 'Provisioned'), ('COMMISSIONED', 'Commissioned'), ('INACTIVE', 'Inactive'), ('UNDER_MAINTENANCE', 'Under Maintenance'), ('FAULTY', 'Faulty')], default='PROVISIONED', max_length=20)),
                ('provisioning_date', models.DateField()),
                ('provisioned_by', models.CharField(max_length=100)),
                ('planned_location', models.TextField(help_text='Planned installation location description')),
                ('commissioning_date', models.DateField(blank=True, null=True)),
                ('commissioned_by', models.CharField(blank=True, max_length=100, null=True)),
                ('actual_location', models.TextField(blank=True, help_text='Actual installed location', null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('dmm', models.CharField(choices=[('Option1', 'Option1'), ('Option2', 'Option2')], max_length=20)),
                ('secondary_connection', models.CharField(choices=[('SC1', 'SC1'), ('SC2', 'SC2'), ('DELTA', 'Delta'), ('WYE', 'Wye')], max_length=20)),
                ('ct_ratio', models.CharField(max_length=20)),
                ('pt_ratio', models.CharField(max_length=20)),
                ('actual_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
