# Generated by Django 5.2.6 on 2025-10-08 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransformerCommissioning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Actual/Cost')),
                ('location', models.CharField(max_length=100, verbose_name='Location')),
                ('commissioning_date', models.DateField(verbose_name='Commissioning Date')),
                ('commissioning_payaze', models.CharField(max_length=255, verbose_name='Commissioning Payaze')),
                ('dmm', models.CharField(choices=[('Option1', 'Option1'), ('Option2', 'Option2')], max_length=20, verbose_name='DMM')),
                ('secondary_connection', models.CharField(choices=[('SC1', 'SC1'), ('SC2', 'SC2'), ('DELTA', 'Delta'), ('WYE', 'Wye')], max_length=20, verbose_name='Secondary Connection')),
                ('ct_ratio', models.CharField(max_length=20, verbose_name='CT Ratio')),
                ('pt_ratio', models.CharField(max_length=20, verbose_name='PT Ratio')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Transformer Commissioning Records',
            },
        ),
        migrations.AlterField(
            model_name='pole',
            name='secondary_connection',
            field=models.CharField(choices=[('SC1', 'SC1'), ('SC2', 'SC2'), ('DELTA', 'Delta'), ('WYE', 'Wye')], max_length=20),
        ),
    ]
