# Generated by Django 5.2.6 on 2025-10-17 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_transformercommissioning_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transformercommissioning',
            options={},
        ),
        migrations.AddField(
            model_name='pole',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='pole',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pole',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='pole',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
        migrations.AddField(
            model_name='pole',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('UNDER_MAINTENANCE', 'Under Maintenance'), ('FAULTY', 'Faulty')], default='ACTIVE', max_length=20),
        ),
    ]
