# Generated by Django 5.2.6 on 2025-10-30 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0003_alter_transformercommissioning_options_pole_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transformercommissioning',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='transformercommissioning',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
